services:
  pocketbase:
    image: stack:latest
    container_name: pocketbase
    ports:
      - "8090:8090"
    volumes:
      - pb_data:/app/pb_data
    restart: unless-stopped

volumes:
  pb_data: